run_dayahead:

run_mpc:

test_profile:
  fields:
    profile:
      required: true
      example: price/nordpool_custom
      selector:
        text:
    options:
      required: false
      example: '{"entity": "sensor.nordpool_kwh_se3_sek_3_10_025"}'
      selector:
        object:
    limit:
      required: false
      default: 10
      selector:
        number:
          min: 1
          max: 500
          mode: box

typical_load_forecast:
  fields:
    day:
      required: true
      example: "2026-08-07"
      selector:
        date:
    average_w:
      required: true
      example: 1200
      selector:
        number:
          min: 0
          mode: box
